lightPathExpressions = {"RBGA":"C.*",
                        "direct":"C[DSV]L",
                        "indriect":"C[DSV][DSVOB].*",
                        "emission":"C[LO]",
                        "background":"CB",
                        "diffuse":"C<RD>.*",
                        "specular":"C<RS[^'coat']>.*",
                        "coat":"C<RS'coat'>.*",
                        "transmission":"C<TS>.*",
                        "sss":"C<TD>.*",
                        "volume":"CV.*",
                        "albedo":"C[DSV]A",
                        "denoise_albedo":"((C<TD>A) (CVA) (C<RD>A))",
                        "diffuse_direct":"C<RD>L",
                        "diffuse_indirect":"C<RD>[DSVOB].*",
                        "diffuse_albedo":"C<RD>A",
                        "specular_coat":"C<RS[^'coat']>L",
                        "specular_indirect":"C<RS[^'coat']>[DSVOB].*",
                        "specular_albedo":"C<RS[^'coat']>A",
                        "coat_direct":"C<RS'coat'>L",
                        "coat_indirect":"C<RS'coat'>[DSVOB].*",
                        "coat_albedo":"C<RS'coat'>A",
                        "sheen":"C<RS'sheen'>.*",
                        "transmission":"C.*",
                        "transmission_direct":"C<TS>L",
                        "transmission_indirect":"C<TS>[DSVOB].*",
                        "transmission_albedo":"C<TS>A",
                        "sheen_direct":"C<RS'sheen'>L",
                        "volume":"CV.*",
                        "sheen_indirect":"C<RS'sheen'>[DSVOB].*",
                        "sheen_albedo":"C<RS'sheen'>A",
                        "sss_direct":"C<TD>L",
                        "sss_indirect":"C<TD>[DSVOB].*",
                        "sss_albedo":"C<TD>A",
                        "volume_direct":"CVL",
                        "volume_indirect":"CV[DSVOB].*",
                        "volume_albedo":"CVA"}

print(lightPathExpressions)

for key in lightPathExpressions:
    print(key)
